accessing
modeDocumentation

"
	16r0000			kOSAModeNull (kOSANullMode)
	16r0001			kOSAModePreventGetSource
	16r0002			kOSAModeCompileIntoContext
	16r0004			kOSAModeAugmentContext
	16r0008			kOSAModeDisplayForHumans
					kOSAModeNeverInteract
					kOSAModeCanInteract
					kOSAModeAlwaysInteract
					kOSAModeDontReconnect
	16r0040			kOSAModeCantSwitchLayer
	16r1000			kOSAModeDoRecord
	16r4000			kOSAModeDontStoreParent"