debian/pharo6-vm-core-resources/usr/bin/pharo6-64-ui	usr/bin
debian/pharo6-vm-core-resources/usr/share/applications/pharo6-64-ui.desktop usr/share/applications
results/lib/pharo/*/B3DAcceleratorPlugin.so		usr/lib/x86_64-linux-gnu/pharo6-vm
results/lib/pharo/*/vm-display-fbdev.so			usr/lib/x86_64-linux-gnu/pharo6-vm
results/lib/pharo/*/vm-display-X11.so			usr/lib/x86_64-linux-gnu/pharo6-vm
results/lib/pharo/*/vm-sound-ALSA.so			usr/lib/x86_64-linux-gnu/pharo6-vm
results/lib/pharo/*/vm-sound-OSS.so			usr/lib/x86_64-linux-gnu/pharo6-vm
results/lib/pharo/*/vm-sound-pulse.so			usr/lib/x86_64-linux-gnu/pharo6-vm
