android template generation
setupAndroidRessources
	'../build/res/' ensureDirectory.
	'../build/res/values/' ensureDirectory.
	'../build/res/layout-xlarge-land/' ensureDirectory.
	'../build/res/layout-xlarge/' ensureDirectory.
	'../build/res/layout-sw720dp/' ensureDirectory.
	'../build/res/layout-sw600dp/' ensureDirectory.
	'../build/res/layout-large/' ensureDirectory.
	'../build/res/layout/' ensureDirectory.
	'../build/res/drawable/' ensureDirectory.
	'../build/jni/' ensureDirectory.
	'../build/assets/' ensureDirectory.
	