primitives-callouts
primFFICallFloatResult: result "<Alien>" floatParmsSignature: byteArray "<ByteArray | nil>" with: firstArg "<Alien | Integer | Double> ^<Alien>" with: secondArg "<Alien | Integer | Double> ^<Alien>" with: thirdArg "<Alien | Integer | Double> ^<Alien>" with: fourthArg "<Alien | Integer | Double> ^<Alien>" with: fifthArg "<Alien | Integer | Double> ^<Alien>" with: sixthArg "<Alien | Integer | Double> ^<Alien>" with: arg7 "<Alien | Integer | Double> ^<Alien>" 
	
	<primitive: 'primCallOutFloatReturnWithFloatParms' error: errorCode module: 'IA32ABI'>
	^ self primitiveFailed