initialize-release
literals: literalSequence instructions: instructionSequence numArgs: nArgs numTemps: nTemps frameSize: frameSizeNum primitive: primitiveIndex flag: flagBoolean signFlag: signFlagBoolean trailer: methodTrailer methodClass: class selector: aSelector compiledMethodClass: classOfCompiledMethod
	literals := literalSequence.
	instructions := instructionSequence.
	numArgs := nArgs.
	numTemps := nTemps.
	frameSize := frameSizeNum.
	primitive := primitiveIndex.
	flag := flagBoolean.
	signFlag := signFlagBoolean.
	trailer := methodTrailer.
	methodClass := class.
	selector := aSelector.
	compiledMethodClass := classOfCompiledMethod