/* Automatically generated by
	SmartSyntaxPluginCodeGenerator VMMaker.oscog-EstebanLorenzano.775 uuid: f5793532-317f-4d15-bf1d-2441fe087fc4
   from
	ClipboardExtendedPlugin VMMaker.oscog-EstebanLorenzano.775 uuid: f5793532-317f-4d15-bf1d-2441fe087fc4
 */
static char __buildInfo[] = "ClipboardExtendedPlugin VMMaker.oscog-EstebanLorenzano.775 uuid: f5793532-317f-4d15-bf1d-2441fe087fc4 " __DATE__ ;



#include <math.h>
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <time.h>

/* Default EXPORT macro that does nothing (see comment in sq.h): */
#define EXPORT(returnType) returnType

/* Do not include the entire sq.h file but just those parts needed. */
/*  The virtual machine proxy definition */
#include "sqVirtualMachine.h"
/* Configuration options */
#include "sqConfig.h"
/* Platform specific definitions */
#include "sqPlatformSpecific.h"

#define true 1
#define false 0
#define null 0  /* using 'null' because nil is predefined in Think C */
#ifdef SQUEAK_BUILTIN_PLUGIN
#undef EXPORT
// was #undef EXPORT(returnType) but screws NorCroft cc
#define EXPORT(returnType) static returnType
#endif

#include "sqMemoryAccess.h"


/*** Constants ***/


/*** Function Prototypes ***/
static VirtualMachine * getInterpreter(void);
EXPORT(const char*) getModuleName(void);
static sqInt halt(void);
EXPORT(sqInt) ioAddClipboardData(void);
EXPORT(sqInt) ioClearClipboard(void);
EXPORT(sqInt) ioCreateClipboard(void);
EXPORT(sqInt) ioGetClipboardFormat(void);
EXPORT(sqInt) ioReadClipboardData(void);
static sqInt msg(char *s);
EXPORT(sqInt) setInterpreter(struct VirtualMachine*anInterpreter);
static sqInt sqAssert(sqInt aBool);


/*** Variables ***/

#if !defined(SQUEAK_BUILTIN_PLUGIN)
static sqInt (*failed)(void);
static void * (*firstIndexableField)(sqInt oop);
static sqInt (*isBytes)(sqInt oop);
static sqInt (*nilObject)(void);
static sqInt (*pop)(sqInt nItems);
static sqInt (*popthenPush)(sqInt nItems, sqInt oop);
static sqInt (*positive32BitIntegerFor)(sqInt integerValue);
static sqInt (*positive32BitValueOf)(sqInt oop);
static sqInt (*slotSizeOf)(sqInt oop);
static sqInt (*stackIntegerValue)(sqInt offset);
static sqInt (*stackValue)(sqInt offset);
static sqInt (*success)(sqInt aBoolean);
#else /* !defined(SQUEAK_BUILTIN_PLUGIN) */
extern sqInt failed(void);
extern void * firstIndexableField(sqInt oop);
extern sqInt isBytes(sqInt oop);
extern sqInt nilObject(void);
extern sqInt pop(sqInt nItems);
extern sqInt popthenPush(sqInt nItems, sqInt oop);
extern sqInt positive32BitIntegerFor(sqInt integerValue);
extern sqInt positive32BitValueOf(sqInt oop);
extern sqInt slotSizeOf(sqInt oop);
extern sqInt stackIntegerValue(sqInt offset);
extern sqInt stackValue(sqInt offset);
extern sqInt success(sqInt aBoolean);
extern
#endif
struct VirtualMachine* interpreterProxy;
static const char *moduleName =
#ifdef SQUEAK_BUILTIN_PLUGIN
	"ClipboardExtendedPlugin VMMaker.oscog-EstebanLorenzano.775 (i)"
#else
	"ClipboardExtendedPlugin VMMaker.oscog-EstebanLorenzano.775 (e)"
#endif
;



/*	Note: This is coded so that plugins can be run from Squeak. */

static VirtualMachine *
getInterpreter(void)
{
	// InterpreterPlugin>>#getInterpreter
	return interpreterProxy;
}


/*	Note: This is hardcoded so it can be run from Squeak.
	The module name is used for validating a module *after*
	it is loaded to check if it does really contain the module
	we're thinking it contains. This is important! */

EXPORT(const char*)
getModuleName(void)
{
	// InterpreterPlugin>>#getModuleName
	return moduleName;
}

static sqInt
halt(void)
{
	// InterpreterPlugin>>#halt
	;
	return 0;
}

EXPORT(sqInt)
ioAddClipboardData(void)
{
	// ClipboardExtendedPlugin>>#ioAddClipboardData
	char *aFormat;
	sqInt clipboard;
	sqInt clipboardAddress;
	char *data;
	sqInt dataLength;
	sqInt formatLength;

	clipboard = stackValue(2);
	success(isBytes(stackValue(1)));
	data = ((char *) (firstIndexableField(stackValue(1))));
	success(isBytes(stackValue(0)));
	aFormat = ((char *) (firstIndexableField(stackValue(0))));
	if (failed()) {
		return null;
	}
	clipboardAddress = positive32BitValueOf(clipboard);
	dataLength = slotSizeOf(((sqInt)(long)(data) - BaseHeaderSize));
	formatLength = slotSizeOf(((sqInt)(long)(aFormat) - BaseHeaderSize));
	sqPasteboardPutItemFlavordatalengthformatTypeformatLength(clipboardAddress, data, dataLength, aFormat, formatLength);
	if (failed()) {
		return null;
	}
	pop(3);
	return null;
}

EXPORT(sqInt)
ioClearClipboard(void)
{
	// ClipboardExtendedPlugin>>#ioClearClipboard
	sqInt clipboard;
	sqInt clipboardAddress;

	clipboard = stackValue(0);
	if (failed()) {
		return null;
	}
	clipboardAddress = positive32BitValueOf(clipboard);
	sqPasteboardClear(clipboardAddress);
	if (failed()) {
		return null;
	}
	pop(1);
	return null;
}

EXPORT(sqInt)
ioCreateClipboard(void)
{
	// ClipboardExtendedPlugin>>#ioCreateClipboard
	sqInt clipboardAddress;

	clipboardAddress = positive32BitIntegerFor(sqCreateClipboard());
	if (failed()) {
		return null;
	}
	popthenPush(1, clipboardAddress);
	return null;
}

EXPORT(sqInt)
ioGetClipboardFormat(void)
{
	// ClipboardExtendedPlugin>>#ioGetClipboardFormat
	sqInt clipboard;
	sqInt clipboardAddress;
	sqInt formatNumber;
	sqInt itemCount;
	sqInt _return_value;

	clipboard = stackValue(1);
	formatNumber = stackIntegerValue(0);
	if (failed()) {
		return null;
	}
	clipboardAddress = positive32BitValueOf(clipboard);
	itemCount = sqPasteboardGetItemCount(clipboardAddress);
	if (itemCount > 0) {
_return_value = sqPasteboardCopyItemFlavorsitemNumber(clipboardAddress, formatNumber);
		if (failed()) {
			return null;
		}
		popthenPush(3, _return_value);
		return null;
	}
	_return_value = nilObject();
	if (failed()) {
		return null;
	}
	popthenPush(3, _return_value);
	return null;
}

EXPORT(sqInt)
ioReadClipboardData(void)
{
	// ClipboardExtendedPlugin>>#ioReadClipboardData
	sqInt clipboard;
	sqInt clipboardAddress;
	char *format;
	sqInt formatLength;
	sqInt _return_value;

	clipboard = stackValue(1);
	success(isBytes(stackValue(0)));
	format = ((char *) (firstIndexableField(stackValue(0))));
	if (failed()) {
		return null;
	}
	clipboardAddress = positive32BitValueOf(clipboard);
	formatLength = slotSizeOf(((sqInt)(long)(format) - BaseHeaderSize));
	_return_value = sqPasteboardCopyItemFlavorDataformatformatLength(clipboardAddress, format, formatLength);
	if (failed()) {
		return null;
	}
	popthenPush(3, _return_value);
	return null;
}

static sqInt
msg(char *s)
{
	// InterpreterPlugin>>#msg:
	fprintf(stderr, "\n%s: %s", moduleName, s);
	return 0;
}


/*	Note: This is coded so that it can be run in Squeak. */

EXPORT(sqInt)
setInterpreter(struct VirtualMachine*anInterpreter)
{
	// InterpreterPlugin>>#setInterpreter:
	sqInt ok;

	interpreterProxy = anInterpreter;
	ok = ((interpreterProxy->majorVersion()) == (VM_PROXY_MAJOR))
	 && ((interpreterProxy->minorVersion()) >= (VM_PROXY_MINOR));
	if (ok) {

#if !defined(SQUEAK_BUILTIN_PLUGIN)
		failed = interpreterProxy->failed;
		firstIndexableField = interpreterProxy->firstIndexableField;
		isBytes = interpreterProxy->isBytes;
		nilObject = interpreterProxy->nilObject;
		pop = interpreterProxy->pop;
		popthenPush = interpreterProxy->popthenPush;
		positive32BitIntegerFor = interpreterProxy->positive32BitIntegerFor;
		positive32BitValueOf = interpreterProxy->positive32BitValueOf;
		slotSizeOf = interpreterProxy->slotSizeOf;
		stackIntegerValue = interpreterProxy->stackIntegerValue;
		stackValue = interpreterProxy->stackValue;
		success = interpreterProxy->success;
#endif /* !defined(SQUEAK_BUILTIN_PLUGIN) */
	}
	return ok;
}

static sqInt
sqAssert(sqInt aBool)
{
	// SmartSyntaxInterpreterPlugin>>#sqAssert:
	/* missing DebugCode */;
}


#ifdef SQUEAK_BUILTIN_PLUGIN

void* ClipboardExtendedPlugin_exports[][3] = {
	{"ClipboardExtendedPlugin", "getModuleName", (void*)getModuleName},
	{"ClipboardExtendedPlugin", "ioAddClipboardData\000\000", (void*)ioAddClipboardData},
	{"ClipboardExtendedPlugin", "ioClearClipboard\000\000", (void*)ioClearClipboard},
	{"ClipboardExtendedPlugin", "ioCreateClipboard\000\377", (void*)ioCreateClipboard},
	{"ClipboardExtendedPlugin", "ioGetClipboardFormat\000\000", (void*)ioGetClipboardFormat},
	{"ClipboardExtendedPlugin", "ioReadClipboardData\000\000", (void*)ioReadClipboardData},
	{"ClipboardExtendedPlugin", "setInterpreter", (void*)setInterpreter},
	{NULL, NULL, NULL}
};

#else /* ifdef SQ_BUILTIN_PLUGIN */

signed char ioAddClipboardDataAccessorDepth = 0;
signed char ioClearClipboardAccessorDepth = 0;
signed char ioGetClipboardFormatAccessorDepth = 0;
signed char ioReadClipboardDataAccessorDepth = 0;

#endif /* ifdef SQ_BUILTIN_PLUGIN */
